# Generated by Django 3.1.1 on 2020-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('insert_date', models.DateTimeField(blank=True, db_column='INSERT_DATE', null=True)),
            ],
            options={
                'db_table': 'INDICATORS',
                'managed': False,
            },
        ),
    ]
